# Generated by Django 4.2.13 on 2024-07-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='never_made',
            field=models.BooleanField(default=False),
        ),
    ]
